/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `account` varchar(30) NOT NULL,
  `passwd` varchar(30) NOT NULL,
  `name` varchar(30) NOT NULL,
  `classname` varchar(30) NOT NULL)
 ENGINE=InnoDB;

